name = "speedup"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# 在这里设置您的环境变量
TARGET_DOMAIN = "mymaskking.ggff.net"
USE_HTTPS = "true" 
www = "hexo-blog.mymaskking.ggff.net"
n8n = "mask139-n8n.hf.space"